### ISSUE TITLE
chose the subject

### ISSUE THREAD

**Issue by theseawolves** [LearnInovationNature/team#1]

**Comment by LearnInovationNature** [comment]
目前市场上的范围较广的应用有：游戏类、交通出行类（百度地图、车来了）、电商类（淘宝、京东）、社交类（微信）。如上所述的几类应用，开发起来的成本也大，类似的产品太多，也不容易找到突破点。我的想法是，找一个有意思的想法，分析下可行性，试下。
1、基于我自己的爱好的一个想法。
动机：利用手机的拍照功能，开发一个应用，对一个人书写的汉字的模式进行匹配优化，指导一个人的书法，特别是小孩子的。其实每个人都有自己的书写习惯，这样的习惯形成以后，很难改变，但每个人的书写习惯都能形成个性的好看的字体的可能。可以利用图象识别中的模式识别对每个人的书写习惯进行微调，使其变得好看一些。
受众：可能偏小众一些。这样的应用用户不多，但我觉得有点意思。
条件：有好的服务器资源进行图相处理，客户端负责图相的采集和结果的呈现。需要采集很多人的字体样本进行研究；还需要一定图相处理技术。
2、基于手机拍照功能可能的应用
a、用手机拍照功能，判断一个水果的新鲜度。
b、通过拍照或者在线读屏幕，来实现 消消看、连连看，类似手游的外挂应用，它启动后，可以自动识别当前屏幕或者照片里的图案，把符合的模式显示出来。（PS：有些人就喜欢通过外挂来找优越感）
暂时想到的三个想法，随后想到的再加进来。MK用的不熟练。

**Comment by LearnInovationNature** [comment]
经过这周三天，每天晚上投入一个小时的尝试。发觉我自己，还是更喜欢安全渗透这方面的技术，对前端JS技术提不起来兴趣。所以，还是早点退出了。抱歉啊。

**Comment by theseawolves** [comment]
没关系。本来就是松散的组织的。书法的想法有意思，不过对图像处理技术要求有点高。。。
